# Site settings
title: PM2
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Expert process manager for production Node.js applications. Load balancer, logs facility,
  startup script, micro service management, at a glance.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pm2.keymetrics.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

sass:
  sass_dir: _sass

# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink']

permalink: /blog/:year/:month/:day/:title
paginate: 1

#gems: ['jekyll-lunr-js-search']

lunr_search:
  js_dir: "../scripts"
